<?xml version="1.1" encoding="UTF-8"?>
<linked-hash-map>
  <entry>
    <string>2</string>
    <Tag plugin="workflow-support@943.v8b_0d01a_7b_a_08">
      <node class="org.jenkinsci.plugins.workflow.graph.FlowStartNode" plugin="workflow-api@1358.vfb_5780da_64cb_">
        <parentIds/>
        <id>2</id>
      </node>
      <actions>
        <wf.a.TimingAction plugin="workflow-api@1358.vfb_5780da_64cb_">
          <startTime>1756948174766</startTime>
        </wf.a.TimingAction>
        <wf.a.ErrorAction plugin="workflow-api@1358.vfb_5780da_64cb_">
          <error class="org.jenkinsci.plugins.workflow.steps.FlowInterruptedException" plugin="workflow-step-api@678.v3ee58b_469476">
            <stackTrace>
              <trace>PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.interrupt(CpsFlowExecution.java:1232)</trace>
              <trace>PluginClassLoader for workflow-job//org.jenkinsci.plugins.workflow.job.WorkflowRun$2.lambda$interrupt$0(WorkflowRun.java:397)</trace>
              <trace>jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)</trace>
              <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)</trace>
              <trace>java.base/java.util.concurrent.FutureTask.run(Unknown Source)</trace>
              <trace>java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)</trace>
              <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)</trace>
              <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)</trace>
              <trace>java.base/java.lang.Thread.run(Unknown Source)</trace>
            </stackTrace>
            <suppressedExceptions>
              <wf.a.ErrorAction_-ErrorId plugin="workflow-api@1358.vfb_5780da_64cb_">
                <stackTrace/>
                <suppressedExceptions class="empty-list"/>
                <uuid>ab00f1d7-1aba-4039-b95c-4dcd24aa9a84</uuid>
              </wf.a.ErrorAction_-ErrorId>
            </suppressedExceptions>
            <result>
              <name>ABORTED</name>
              <ordinal>4</ordinal>
              <color>ABORTED</color>
              <completeBuild>false</completeBuild>
            </result>
            <causes class="java.util.Arrays$ArrayList">
              <a class="jenkins.model.CauseOfInterruption-array">
                <jenkins.model.CauseOfInterruption_-UserInterruption>
                  <user>team2</user>
                </jenkins.model.CauseOfInterruption_-UserInterruption>
              </a>
            </causes>
            <actualInterruption>true</actualInterruption>
          </error>
        </wf.a.ErrorAction>
      </actions>
    </Tag>
  </entry>
  <entry>
    <string>3</string>
    <Tag plugin="workflow-support@943.v8b_0d01a_7b_a_08">
      <node class="org.jenkinsci.plugins.workflow.graph.FlowEndNode" plugin="workflow-api@1358.vfb_5780da_64cb_">
        <parentIds>
          <string>2</string>
        </parentIds>
        <id>3</id>
        <startId>2</startId>
        <result>
          <name>ABORTED</name>
          <ordinal>4</ordinal>
          <color>ABORTED</color>
          <completeBuild>false</completeBuild>
        </result>
      </node>
      <actions>
        <wf.a.ErrorAction plugin="workflow-api@1358.vfb_5780da_64cb_">
          <error class="org.jenkinsci.plugins.workflow.steps.FlowInterruptedException" reference="../../../../../entry/Tag/actions/wf.a.ErrorAction/error"/>
        </wf.a.ErrorAction>
        <wf.a.TimingAction plugin="workflow-api@1358.vfb_5780da_64cb_">
          <startTime>1756948175195</startTime>
        </wf.a.TimingAction>
      </actions>
    </Tag>
  </entry>
</linked-hash-map>